import json

# The initial dataset should be representative of the data the model will be used on,
# in order to perform well on new, unseen data.

# Currently dataset is calibrated and tweaked for the best fit for (my own) personal usage.


class CategoryDataset:

    def __init__(self):
        self.dataset = [
            ("BUS/MRT", "Transportation"),
            ("UNIQLO SINGAPORE PTE", "Wants"),
            ("UNIQLO PTE", "Wants"),
            ("UNIQLO", "Wants"),
            ("BILL", "Bill"),
            ("STBILL", "Bill"),
            ("STBILL", "Bill"),
            ("STBILL", "Bill"),
            ("STBILL", "Bill"),
            ("bill", "Bill"),
            ("ST_bill", "Bill"),
            ("APPLE.COM/BILL", "Bill"),
            ("bills", "Bill"),
            ("Grab", "Transportation"),
            ("Grab*", "Transportation"),
            ("Grab* bb7d29d7cbadc567", "Transportation"),
            ("Grab * bcc1d2sd23csdfas67", "Transportation"),
            ("BUS/MRT 23412525", "Transportation"),
            ("BUS/MRT 234234", "Transportation"),
            ("BUS/MRT 234234254", "Transportation"),
            ("BUS/MRT 346345345", "Transportation"),
            ("BUS/MRT 1234234", "Transportation"),
            ("BUS/MRT 4636346", "Transportation"),
            ("BUS/MRT 2342342", "Transportation"),
            ("ELECTRICITY BILL SINGAPORE POWER", "Bills"),
            ("WATER BILL PUB SINGAPORE", "Bills"),
            ("TELECOMMUNICATIONS BILL SINGTEL", "Bills"),
            ("INTERNET BILL STARHUB", "Bills"),
            ("GAS BILL CITYGAS", "Bills"),
            ("CREDIT CARD BILL CITIBANK", "Bills"),
            ("LOAN REPAYMENT BANK OF CHINA", "Bills"),
            ("INSURANCE PREMIUM PRUDENTIAL", "Bills"),
            ("PROPERTY TAX HDB", "Bills"),
            ("CAR INSURANCE AXA", "Bills"),
            ("CABLE TV BILL ASTRO", "Bills"),
            ("RENT BILL UOB", "Bills"),
            ("MEDICAL BILL KK HOSPITAL", "Bills"),
            ("GRAB A-324341235", "Transportation"),
            ("BUS/MRT 235234234", "Transportation"),
            ("LAZADA", "Wants"),
            ("ACTIVESG SPORT", "Wants"),
            ("BUS/MRT 234123452", "Transportation"),
            ("NTUC FP-WHITE SANDS", "Wants"),
            ("GRAB-RIDE A-324341235", "Transportation"),
            ("MRT RIDE 235234234", "Transportation"),
            ("LAZADA.SG", "Wants"),
            ("ACTIVESG FITNESS", "Wants"),
            ("BUS RIDE 234123452", "Transportation"),
            ("NTUC FAIRPRICE-WHITE SANDS", "Wants"),
            ("GRAB-CAR A-324341235", "Transportation"),
            ("MRT TICKET 235234234", "Transportation"),
            ("LAZADA.COM", "Wants"),
            ("ACTIVESG MEMBERSHIP", "Wants"),
            ("BUS TICKET 234123452", "Transportation"),
            ("NTUC FAIRPRICE WHITE SANDS", "Wants"),
            ("SINGTEL BILL", "Bills"),
            ("SP GROUP - ELECTRICITY BILL", "Bills"),
            ("STARHUB BILL", "Bills"),
            ("SINGAPORE POWER - GAS BILL", "Bills"),
            ("M1 BILL", "Bills"),
            ("SINGAPORE WATER BILL", "Bills"),
            ("KEPPEL DC REIT - SERVER RENTAL BILL", "Bills"),
            ("KEPCO S PORE PTE LTD - MONTHLY BILL", "Bills"),
            ("SINGAPORE LAND AUTHORITY - LAND RENT BILL", "Bills"),
            ("SINGAPORE TELECOMMUNICATIONS LIMITED - BILL", "Bills"),
            ("AMAZON.COM", "Wants"),
            ("SHOPEE SINGAPORE", "Wants"),
            ("QOO10 SINGAPORE", "Wants"),
            ("TAOBAO", "Wants"),
            ("LAZADA SINGAPORE", "Wants"),
            ("SHOPBACK", "Wants"),
            ("CAROUSELL", "Wants"),
            ("ZALORA SINGAPORE", "Wants"),
            ("ASOS.COM", "Wants"),
            ("STEAM PURCHASE", "Wants"),
            ("JFE-AKIMITSU", "Wants"),
            ("SHEIN.COM", "Wants"),
            ("UNIQLO SINGAPORE PTE", "Wants"),
            ("UNIQLO PTE", "Wants"),
            ("UNIQLO", "Wants"),
            ("ZARA SINGAPORE", "Wants"),
            ("H&M SINGAPORE", "Wants"),
            ("MANGO SINGAPORE", "Wants"),
            ("TOPSHOP SINGAPORE", "Wants"),
            ("FOREVER 21 SINGAPORE", "Wants"),
            ("BERSHKA SINGAPORE", "Wants"),
            ("KFC SINGAPORE", "Food"),
            ("XIN WANG- VELOCITY", "Food"),
        ]
        self.keywords_food = ["SUKIYA", "SAIZERIYA", "YAKINIKU",
                              "MCDONALD'S", "7-ELEVEN", "FOOD", "DON DON DONKI", "MONSTER CURRY",
                              "XIN WANG", "KFC", "SWENSEN'S", "SUSHI", "MAKI", "LAO HUO TANG", "Dessert", "LUNCH",
                              "KOPITIAM"
                              ]

    def json_build(self):
        with open('dataset.json', 'w') as f:
            json.dump(self.dataset, f)
        with open('keywords_food.json', 'w') as f:
            json.dump(self.keywords_food, f)
